# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_create_layer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateLayerDialog(object):
    def setupUi(self, CreateLayerDialog):
        CreateLayerDialog.setObjectName("CreateLayerDialog")
        CreateLayerDialog.resize(500, 220)
        self.lblFileName = QtWidgets.QLabel(CreateLayerDialog)
        self.lblFileName.setGeometry(QtCore.QRect(10, 140, 131, 21))
        self.lblFileName.setObjectName("lblFileName")
        self.txtMapName = QtWidgets.QLineEdit(CreateLayerDialog)
        self.txtMapName.setGeometry(QtCore.QRect(140, 140, 121, 21))
        self.txtMapName.setStyleSheet("background-color: #fff79a")
        self.txtMapName.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.txtMapName.setObjectName("txtMapName")
        self.btnCreate = QtWidgets.QPushButton(CreateLayerDialog)
        self.btnCreate.setGeometry(QtCore.QRect(280, 180, 93, 28))
        self.btnCreate.setObjectName("btnCreate")
        self.btnCancel = QtWidgets.QPushButton(CreateLayerDialog)
        self.btnCancel.setGeometry(QtCore.QRect(390, 180, 93, 28))
        self.btnCancel.setObjectName("btnCancel")
        self.txtMapTitle = QtWidgets.QLineEdit(CreateLayerDialog)
        self.txtMapTitle.setGeometry(QtCore.QRect(140, 100, 331, 21))
        self.txtMapTitle.setStyleSheet("background-color: #fff79a")
        self.txtMapTitle.setObjectName("txtMapTitle")
        self.lblGroupName = QtWidgets.QLabel(CreateLayerDialog)
        self.lblGroupName.setGeometry(QtCore.QRect(10, 100, 131, 21))
        self.lblGroupName.setObjectName("lblGroupName")
        self.lblFileName2 = QtWidgets.QLabel(CreateLayerDialog)
        self.lblFileName2.setGeometry(QtCore.QRect(270, 140, 201, 21))
        self.lblFileName2.setObjectName("lblFileName2")
        self.cboMapType = QtWidgets.QComboBox(CreateLayerDialog)
        self.cboMapType.setGeometry(QtCore.QRect(140, 30, 271, 22))
        self.cboMapType.setObjectName("cboMapType")
        self.label = QtWidgets.QLabel(CreateLayerDialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 131, 21))
        self.label.setObjectName("label")
        self.frmFileSelect = QtWidgets.QFrame(CreateLayerDialog)
        self.frmFileSelect.setGeometry(QtCore.QRect(0, 50, 481, 41))
        self.frmFileSelect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFileSelect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFileSelect.setObjectName("frmFileSelect")
        self.btnFileSelect = QtWidgets.QPushButton(self.frmFileSelect)
        self.btnFileSelect.setGeometry(QtCore.QRect(420, 10, 51, 23))
        self.btnFileSelect.setObjectName("btnFileSelect")
        self.txtFileSelect = QtWidgets.QLineEdit(self.frmFileSelect)
        self.txtFileSelect.setGeometry(QtCore.QRect(140, 10, 271, 20))
        self.txtFileSelect.setStyleSheet("background-color: #fff79a")
        self.txtFileSelect.setObjectName("txtFileSelect")
        self.lblFile = QtWidgets.QLabel(CreateLayerDialog)
        self.lblFile.setGeometry(QtCore.QRect(10, 70, 121, 21))
        self.lblFile.setText("")
        self.lblFile.setObjectName("lblFile")
        self.frmFileSelect.raise_()
        self.lblFileName.raise_()
        self.txtMapName.raise_()
        self.btnCreate.raise_()
        self.btnCancel.raise_()
        self.txtMapTitle.raise_()
        self.lblGroupName.raise_()
        self.lblFileName2.raise_()
        self.cboMapType.raise_()
        self.label.raise_()
        self.lblFile.raise_()

        self.retranslateUi(CreateLayerDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateLayerDialog)
        CreateLayerDialog.setTabOrder(self.cboMapType, self.txtFileSelect)
        CreateLayerDialog.setTabOrder(self.txtFileSelect, self.btnFileSelect)
        CreateLayerDialog.setTabOrder(self.btnFileSelect, self.txtMapTitle)
        CreateLayerDialog.setTabOrder(self.txtMapTitle, self.txtMapName)
        CreateLayerDialog.setTabOrder(self.txtMapName, self.btnCreate)
        CreateLayerDialog.setTabOrder(self.btnCreate, self.btnCancel)

    def retranslateUi(self, CreateLayerDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateLayerDialog.setWindowTitle(_translate("CreateLayerDialog", "Create Layer"))
        self.lblFileName.setText(_translate("CreateLayerDialog", "File Name"))
        self.txtMapName.setPlaceholderText(_translate("CreateLayerDialog", "e.g. scenario01"))
        self.btnCreate.setText(_translate("CreateLayerDialog", "Create"))
        self.btnCancel.setText(_translate("CreateLayerDialog", "Cancel"))
        self.txtMapTitle.setPlaceholderText(_translate("CreateLayerDialog", "e.g. 1. Major geosites"))
        self.lblGroupName.setText(_translate("CreateLayerDialog", "Map Name"))
        self.lblFileName2.setText(_translate("CreateLayerDialog", " (single-byte character only)"))
        self.label.setText(_translate("CreateLayerDialog", "Select Map Type"))
        self.btnFileSelect.setText(_translate("CreateLayerDialog", "Select"))

