# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geolib3
                                 A QGIS plugin
 This plugin provides functions for creating geological map.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-16
        copyright            : (C) 2022 by Dank Co., Ltd.
        email                : ykarata@geotrekking.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Geolib3 class from file Geolib3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geolib3 import Geolib3
    return Geolib3(iface)
