# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_create_subject_layer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateSubjectLayerDialog(object):
    def setupUi(self, CreateSubjectLayerDialog):
        CreateSubjectLayerDialog.setObjectName("CreateSubjectLayerDialog")
        CreateSubjectLayerDialog.resize(623, 260)
        self.lblFileName = QtWidgets.QLabel(CreateSubjectLayerDialog)
        self.lblFileName.setGeometry(QtCore.QRect(10, 140, 151, 21))
        self.lblFileName.setObjectName("lblFileName")
        self.txtMapName = QtWidgets.QLineEdit(CreateSubjectLayerDialog)
        self.txtMapName.setGeometry(QtCore.QRect(170, 140, 181, 21))
        self.txtMapName.setStyleSheet("background-color: #fff79a")
        self.txtMapName.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.txtMapName.setObjectName("txtMapName")
        self.btnCreate = QtWidgets.QPushButton(CreateSubjectLayerDialog)
        self.btnCreate.setGeometry(QtCore.QRect(400, 210, 93, 28))
        self.btnCreate.setObjectName("btnCreate")
        self.btnCancel = QtWidgets.QPushButton(CreateSubjectLayerDialog)
        self.btnCancel.setGeometry(QtCore.QRect(510, 210, 93, 28))
        self.btnCancel.setObjectName("btnCancel")
        self.txtMapTitle = QtWidgets.QLineEdit(CreateSubjectLayerDialog)
        self.txtMapTitle.setGeometry(QtCore.QRect(170, 170, 371, 21))
        self.txtMapTitle.setStyleSheet("background-color: #fff79a")
        self.txtMapTitle.setObjectName("txtMapTitle")
        self.lblGroupName = QtWidgets.QLabel(CreateSubjectLayerDialog)
        self.lblGroupName.setGeometry(QtCore.QRect(10, 170, 151, 21))
        self.lblGroupName.setObjectName("lblGroupName")
        self.lblFileName2 = QtWidgets.QLabel(CreateSubjectLayerDialog)
        self.lblFileName2.setGeometry(QtCore.QRect(360, 140, 251, 21))
        self.lblFileName2.setObjectName("lblFileName2")
        self.cboMapType = QtWidgets.QComboBox(CreateSubjectLayerDialog)
        self.cboMapType.setGeometry(QtCore.QRect(170, 20, 371, 22))
        self.cboMapType.setObjectName("cboMapType")
        self.lblMapType = QtWidgets.QLabel(CreateSubjectLayerDialog)
        self.lblMapType.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.lblMapType.setObjectName("lblMapType")
        self.frmFileSelect = QtWidgets.QFrame(CreateSubjectLayerDialog)
        self.frmFileSelect.setGeometry(QtCore.QRect(10, 50, 601, 51))
        self.frmFileSelect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFileSelect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFileSelect.setObjectName("frmFileSelect")
        self.btnFileSelect = QtWidgets.QPushButton(self.frmFileSelect)
        self.btnFileSelect.setGeometry(QtCore.QRect(540, 20, 51, 23))
        self.btnFileSelect.setObjectName("btnFileSelect")
        self.txtFileSelect = QtWidgets.QLineEdit(self.frmFileSelect)
        self.txtFileSelect.setGeometry(QtCore.QRect(160, 20, 371, 20))
        self.txtFileSelect.setStyleSheet("background-color: #fff79a")
        self.txtFileSelect.setObjectName("txtFileSelect")
        self.lblFile = QtWidgets.QLabel(self.frmFileSelect)
        self.lblFile.setGeometry(QtCore.QRect(0, 20, 151, 21))
        self.lblFile.setText("")
        self.lblFile.setObjectName("lblFile")
        self.lblFolderName = QtWidgets.QLabel(CreateSubjectLayerDialog)
        self.lblFolderName.setGeometry(QtCore.QRect(10, 110, 151, 21))
        self.lblFolderName.setObjectName("lblFolderName")
        self.txtFolderSelect = QtWidgets.QLineEdit(CreateSubjectLayerDialog)
        self.txtFolderSelect.setGeometry(QtCore.QRect(170, 110, 371, 20))
        self.txtFolderSelect.setStyleSheet("background-color: #fff79a")
        self.txtFolderSelect.setObjectName("txtFolderSelect")
        self.btnFolderSelect = QtWidgets.QPushButton(CreateSubjectLayerDialog)
        self.btnFolderSelect.setGeometry(QtCore.QRect(550, 110, 51, 23))
        self.btnFolderSelect.setObjectName("btnFolderSelect")
        self.frmFileSelect.raise_()
        self.lblFileName.raise_()
        self.txtMapName.raise_()
        self.btnCreate.raise_()
        self.btnCancel.raise_()
        self.txtMapTitle.raise_()
        self.lblGroupName.raise_()
        self.lblFileName2.raise_()
        self.cboMapType.raise_()
        self.lblMapType.raise_()
        self.lblFolderName.raise_()
        self.txtFolderSelect.raise_()
        self.btnFolderSelect.raise_()

        self.retranslateUi(CreateSubjectLayerDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateSubjectLayerDialog)
        CreateSubjectLayerDialog.setTabOrder(self.cboMapType, self.txtFileSelect)
        CreateSubjectLayerDialog.setTabOrder(self.txtFileSelect, self.btnFileSelect)
        CreateSubjectLayerDialog.setTabOrder(self.btnFileSelect, self.txtFolderSelect)
        CreateSubjectLayerDialog.setTabOrder(self.txtFolderSelect, self.btnFolderSelect)
        CreateSubjectLayerDialog.setTabOrder(self.btnFolderSelect, self.txtMapName)
        CreateSubjectLayerDialog.setTabOrder(self.txtMapName, self.txtMapTitle)
        CreateSubjectLayerDialog.setTabOrder(self.txtMapTitle, self.btnCreate)
        CreateSubjectLayerDialog.setTabOrder(self.btnCreate, self.btnCancel)

    def retranslateUi(self, CreateSubjectLayerDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateSubjectLayerDialog.setWindowTitle(_translate("CreateSubjectLayerDialog", "Create Geological Map Layer"))
        self.lblFileName.setText(_translate("CreateSubjectLayerDialog", "File Name"))
        self.txtMapName.setPlaceholderText(_translate("CreateSubjectLayerDialog", "e.g. geomap01"))
        self.btnCreate.setText(_translate("CreateSubjectLayerDialog", "Create"))
        self.btnCancel.setText(_translate("CreateSubjectLayerDialog", "Cancel"))
        self.txtMapTitle.setPlaceholderText(_translate("CreateSubjectLayerDialog", "e.g. Survey Area Geological Map"))
        self.lblGroupName.setText(_translate("CreateSubjectLayerDialog", "Layer Group Name"))
        self.lblFileName2.setText(_translate("CreateSubjectLayerDialog", "(single-byte character only)"))
        self.lblMapType.setText(_translate("CreateSubjectLayerDialog", "Selet create type"))
        self.btnFileSelect.setText(_translate("CreateSubjectLayerDialog", "Select"))
        self.lblFolderName.setText(_translate("CreateSubjectLayerDialog", "Folder Name"))
        self.btnFolderSelect.setText(_translate("CreateSubjectLayerDialog", "Select"))

