# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_edit_attribute_dockwidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditAttributeDockWidget(object):
    def setupUi(self, EditAttributeDockWidget):
        EditAttributeDockWidget.setObjectName("EditAttributeDockWidget")
        EditAttributeDockWidget.setEnabled(True)
        EditAttributeDockWidget.resize(400, 435)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditAttributeDockWidget.sizePolicy().hasHeightForWidth())
        EditAttributeDockWidget.setSizePolicy(sizePolicy)
        EditAttributeDockWidget.setMinimumSize(QtCore.QSize(290, 400))
        EditAttributeDockWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        EditAttributeDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.txtDescription = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.txtDescription.setGeometry(QtCore.QRect(90, 187, 301, 51))
        self.txtDescription.setObjectName("txtDescription")
        self.grpStyle = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.grpStyle.setGeometry(QtCore.QRect(0, 88, 401, 61))
        self.grpStyle.setObjectName("grpStyle")
        self.cboSymbol = QtWidgets.QComboBox(self.grpStyle)
        self.cboSymbol.setGeometry(QtCore.QRect(90, 30, 221, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cboSymbol.setFont(font)
        self.cboSymbol.setObjectName("cboSymbol")
        self.lblSymbol = QtWidgets.QLabel(self.grpStyle)
        self.lblSymbol.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.lblSymbol.setObjectName("lblSymbol")
        self.btnStyleEdit = QtWidgets.QPushButton(self.grpStyle)
        self.btnStyleEdit.setGeometry(QtCore.QRect(320, 30, 71, 24))
        self.btnStyleEdit.setObjectName("btnStyleEdit")
        self.frmStrDip = QtWidgets.QFrame(self.dockWidgetContents)
        self.frmStrDip.setGeometry(QtCore.QRect(0, 250, 401, 111))
        self.frmStrDip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmStrDip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmStrDip.setObjectName("frmStrDip")
        self.cboStrike2 = QtWidgets.QComboBox(self.frmStrDip)
        self.cboStrike2.setGeometry(QtCore.QRect(180, 10, 51, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cboStrike2.setFont(font)
        self.cboStrike2.setEditable(True)
        self.cboStrike2.setObjectName("cboStrike2")
        self.cboStrike2.addItem("")
        self.cboStrike2.addItem("")
        self.cboStrike2.addItem("")
        self.spnStrike = QtWidgets.QDoubleSpinBox(self.frmStrDip)
        self.spnStrike.setGeometry(QtCore.QRect(120, 10, 60, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spnStrike.setFont(font)
        self.spnStrike.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnStrike.setDecimals(0)
        self.spnStrike.setMaximum(90.0)
        self.spnStrike.setObjectName("spnStrike")
        self.lblStrike = QtWidgets.QLabel(self.frmStrDip)
        self.lblStrike.setGeometry(QtCore.QRect(10, 10, 61, 28))
        self.lblStrike.setObjectName("lblStrike")
        self.lblDip = QtWidgets.QLabel(self.frmStrDip)
        self.lblDip.setGeometry(QtCore.QRect(240, 10, 40, 28))
        self.lblDip.setObjectName("lblDip")
        self.spnDip = QtWidgets.QDoubleSpinBox(self.frmStrDip)
        self.spnDip.setGeometry(QtCore.QRect(280, 10, 60, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spnDip.setFont(font)
        self.spnDip.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnDip.setDecimals(0)
        self.spnDip.setMaximum(90.0)
        self.spnDip.setObjectName("spnDip")
        self.cboStrike1 = QtWidgets.QComboBox(self.frmStrDip)
        self.cboStrike1.setGeometry(QtCore.QRect(70, 10, 50, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cboStrike1.setFont(font)
        self.cboStrike1.setEditable(True)
        self.cboStrike1.setObjectName("cboStrike1")
        self.cboStrike1.addItem("")
        self.cboDip = QtWidgets.QComboBox(self.frmStrDip)
        self.cboDip.setGeometry(QtCore.QRect(340, 10, 51, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cboDip.setFont(font)
        self.cboDip.setEditable(True)
        self.cboDip.setObjectName("cboDip")
        self.cboDip.addItem("")
        self.cboDip.addItem("")
        self.cboDip.addItem("")
        self.cboDip.addItem("")
        self.lblTrend = QtWidgets.QLabel(self.frmStrDip)
        self.lblTrend.setGeometry(QtCore.QRect(100, 50, 71, 21))
        self.lblTrend.setObjectName("lblTrend")
        self.lblPlunge = QtWidgets.QLabel(self.frmStrDip)
        self.lblPlunge.setGeometry(QtCore.QRect(200, 50, 71, 21))
        self.lblPlunge.setObjectName("lblPlunge")
        self.lblRake = QtWidgets.QLabel(self.frmStrDip)
        self.lblRake.setGeometry(QtCore.QRect(300, 50, 71, 21))
        self.lblRake.setObjectName("lblRake")
        self.spnTrend = QtWidgets.QDoubleSpinBox(self.frmStrDip)
        self.spnTrend.setGeometry(QtCore.QRect(100, 70, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spnTrend.setFont(font)
        self.spnTrend.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnTrend.setDecimals(0)
        self.spnTrend.setMaximum(360.0)
        self.spnTrend.setObjectName("spnTrend")
        self.spnRake = QtWidgets.QDoubleSpinBox(self.frmStrDip)
        self.spnRake.setGeometry(QtCore.QRect(300, 70, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spnRake.setFont(font)
        self.spnRake.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnRake.setDecimals(0)
        self.spnRake.setMaximum(90.0)
        self.spnRake.setObjectName("spnRake")
        self.spnPlunge = QtWidgets.QDoubleSpinBox(self.frmStrDip)
        self.spnPlunge.setGeometry(QtCore.QRect(200, 70, 90, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.spnPlunge.setFont(font)
        self.spnPlunge.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnPlunge.setDecimals(0)
        self.spnPlunge.setMaximum(90.0)
        self.spnPlunge.setObjectName("spnPlunge")
        self.btnUpdate = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnUpdate.setGeometry(QtCore.QRect(272, 50, 121, 31))
        self.btnUpdate.setObjectName("btnUpdate")
        self.txtLegend01 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.txtLegend01.setGeometry(QtCore.QRect(90, 157, 301, 21))
        self.txtLegend01.setObjectName("txtLegend01")
        self.lblDescription = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblDescription.setGeometry(QtCore.QRect(10, 187, 71, 51))
        self.lblDescription.setObjectName("lblDescription")
        self.lblLegend01 = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblLegend01.setGeometry(QtCore.QRect(10, 157, 71, 20))
        self.lblLegend01.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend01.setObjectName("lblLegend01")
        self.frmLegend = QtWidgets.QFrame(self.dockWidgetContents)
        self.frmLegend.setGeometry(QtCore.QRect(0, 250, 401, 141))
        self.frmLegend.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmLegend.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmLegend.setObjectName("frmLegend")
        self.txtLegend02 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend02.setGeometry(QtCore.QRect(130, 10, 258, 21))
        self.txtLegend02.setObjectName("txtLegend02")
        self.txtLegend06 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend06.setGeometry(QtCore.QRect(130, 90, 258, 21))
        self.txtLegend06.setObjectName("txtLegend06")
        self.lblLegend07 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend07.setGeometry(QtCore.QRect(10, 111, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend07.setFont(font)
        self.lblLegend07.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend07.setObjectName("lblLegend07")
        self.lblLegend06 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend06.setGeometry(QtCore.QRect(10, 91, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend06.setFont(font)
        self.lblLegend06.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend06.setObjectName("lblLegend06")
        self.txtLegend03 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend03.setGeometry(QtCore.QRect(130, 30, 258, 21))
        self.txtLegend03.setObjectName("txtLegend03")
        self.lblLegend03 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend03.setGeometry(QtCore.QRect(10, 30, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend03.setFont(font)
        self.lblLegend03.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend03.setObjectName("lblLegend03")
        self.txtLegend05 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend05.setGeometry(QtCore.QRect(130, 70, 258, 21))
        self.txtLegend05.setObjectName("txtLegend05")
        self.lblLegend02 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend02.setGeometry(QtCore.QRect(10, 10, 120, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend02.setFont(font)
        self.lblLegend02.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend02.setObjectName("lblLegend02")
        self.lblLegend04 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend04.setGeometry(QtCore.QRect(10, 51, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend04.setFont(font)
        self.lblLegend04.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend04.setObjectName("lblLegend04")
        self.txtLegend07 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend07.setGeometry(QtCore.QRect(130, 110, 258, 21))
        self.txtLegend07.setObjectName("txtLegend07")
        self.txtLegend04 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend04.setGeometry(QtCore.QRect(130, 50, 258, 21))
        self.txtLegend04.setObjectName("txtLegend04")
        self.lblLegend05 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend05.setGeometry(QtCore.QRect(10, 71, 120, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend05.setFont(font)
        self.lblLegend05.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend05.setObjectName("lblLegend05")
        self.txtLayerName = QtWidgets.QLabel(self.dockWidgetContents)
        self.txtLayerName.setGeometry(QtCore.QRect(130, 0, 261, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtLayerName.setFont(font)
        self.txtLayerName.setText("")
        self.txtLayerName.setObjectName("txtLayerName")
        self.txtFeature = QtWidgets.QLabel(self.dockWidgetContents)
        self.txtFeature.setGeometry(QtCore.QRect(130, 20, 261, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtFeature.setFont(font)
        self.txtFeature.setText("")
        self.txtFeature.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtFeature.setObjectName("txtFeature")
        self.lblLayerName = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblLayerName.setGeometry(QtCore.QRect(10, 0, 111, 21))
        self.lblLayerName.setObjectName("lblLayerName")
        self.lblFeature = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblFeature.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.lblFeature.setObjectName("lblFeature")
        self.btnSelectCancel = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnSelectCancel.setGeometry(QtCore.QRect(130, 50, 121, 31))
        self.btnSelectCancel.setObjectName("btnSelectCancel")
        EditAttributeDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(EditAttributeDockWidget)
        QtCore.QMetaObject.connectSlotsByName(EditAttributeDockWidget)
        EditAttributeDockWidget.setTabOrder(self.cboSymbol, self.txtLegend01)
        EditAttributeDockWidget.setTabOrder(self.txtLegend01, self.txtDescription)
        EditAttributeDockWidget.setTabOrder(self.txtDescription, self.cboStrike1)
        EditAttributeDockWidget.setTabOrder(self.cboStrike1, self.spnStrike)
        EditAttributeDockWidget.setTabOrder(self.spnStrike, self.cboStrike2)
        EditAttributeDockWidget.setTabOrder(self.cboStrike2, self.spnDip)
        EditAttributeDockWidget.setTabOrder(self.spnDip, self.cboDip)
        EditAttributeDockWidget.setTabOrder(self.cboDip, self.spnTrend)
        EditAttributeDockWidget.setTabOrder(self.spnTrend, self.spnPlunge)
        EditAttributeDockWidget.setTabOrder(self.spnPlunge, self.spnRake)
        EditAttributeDockWidget.setTabOrder(self.spnRake, self.txtLegend02)
        EditAttributeDockWidget.setTabOrder(self.txtLegend02, self.txtLegend03)
        EditAttributeDockWidget.setTabOrder(self.txtLegend03, self.txtLegend04)
        EditAttributeDockWidget.setTabOrder(self.txtLegend04, self.txtLegend05)
        EditAttributeDockWidget.setTabOrder(self.txtLegend05, self.txtLegend06)
        EditAttributeDockWidget.setTabOrder(self.txtLegend06, self.txtLegend07)
        EditAttributeDockWidget.setTabOrder(self.txtLegend07, self.btnSelectCancel)
        EditAttributeDockWidget.setTabOrder(self.btnSelectCancel, self.btnUpdate)

    def retranslateUi(self, EditAttributeDockWidget):
        _translate = QtCore.QCoreApplication.translate
        EditAttributeDockWidget.setWindowTitle(_translate("EditAttributeDockWidget", "Edit Feature Attribute"))
        self.grpStyle.setTitle(_translate("EditAttributeDockWidget", "Style"))
        self.lblSymbol.setText(_translate("EditAttributeDockWidget", "Symbol"))
        self.btnStyleEdit.setText(_translate("EditAttributeDockWidget", "Edit"))
        self.cboStrike2.setItemText(0, _translate("EditAttributeDockWidget", "E"))
        self.cboStrike2.setItemText(1, _translate("EditAttributeDockWidget", "W"))
        self.cboStrike2.setItemText(2, _translate("EditAttributeDockWidget", "S"))
        self.lblStrike.setText(_translate("EditAttributeDockWidget", "Strike"))
        self.lblDip.setText(_translate("EditAttributeDockWidget", "Dip"))
        self.cboStrike1.setItemText(0, _translate("EditAttributeDockWidget", "N"))
        self.cboDip.setItemText(0, _translate("EditAttributeDockWidget", "E"))
        self.cboDip.setItemText(1, _translate("EditAttributeDockWidget", "W"))
        self.cboDip.setItemText(2, _translate("EditAttributeDockWidget", "N"))
        self.cboDip.setItemText(3, _translate("EditAttributeDockWidget", "S"))
        self.lblTrend.setText(_translate("EditAttributeDockWidget", "Trend"))
        self.lblPlunge.setText(_translate("EditAttributeDockWidget", "Plunge"))
        self.lblRake.setText(_translate("EditAttributeDockWidget", "Rake"))
        self.btnUpdate.setText(_translate("EditAttributeDockWidget", "Save"))
        self.lblDescription.setText(_translate("EditAttributeDockWidget", "Description"))
        self.lblLegend01.setText(_translate("EditAttributeDockWidget", "Legend1"))
        self.lblLegend07.setText(_translate("EditAttributeDockWidget", "Legend7"))
        self.lblLegend06.setText(_translate("EditAttributeDockWidget", "Legend6"))
        self.lblLegend03.setText(_translate("EditAttributeDockWidget", "Legend3"))
        self.lblLegend02.setText(_translate("EditAttributeDockWidget", "Legend2"))
        self.lblLegend04.setText(_translate("EditAttributeDockWidget", "Legend4"))
        self.lblLegend05.setText(_translate("EditAttributeDockWidget", "Legend5"))
        self.lblLayerName.setText(_translate("EditAttributeDockWidget", "Layer:"))
        self.lblFeature.setText(_translate("EditAttributeDockWidget", "Feature ID:"))
        self.btnSelectCancel.setText(_translate("EditAttributeDockWidget", "Cancel select"))

