# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geolib3
                                 A QGIS plugin
 This plugin provides functions to easily create maps for Geoscience library.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-07
        copyright            : (C) 2018 by Dank Co., Ltd.
        email                : yukihiko.karata@nsb-dank.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

def classFactory(iface):
    from .geolib3 import Geolib3
    return Geolib3(iface)
