# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_create_layer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateLayerDialog(object):
    def setupUi(self, CreateLayerDialog):
        CreateLayerDialog.setObjectName("CreateLayerDialog")
        CreateLayerDialog.resize(500, 264)
        self.lblFileName = QtWidgets.QLabel(CreateLayerDialog)
        self.lblFileName.setGeometry(QtCore.QRect(10, 160, 131, 21))
        self.lblFileName.setObjectName("lblFileName")
        self.txtFileName = QtWidgets.QLineEdit(CreateLayerDialog)
        self.txtFileName.setGeometry(QtCore.QRect(140, 160, 121, 21))
        self.txtFileName.setStyleSheet("background-color: #fff79a")
        self.txtFileName.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.txtFileName.setObjectName("txtFileName")
        self.btnCreate = QtWidgets.QPushButton(CreateLayerDialog)
        self.btnCreate.setGeometry(QtCore.QRect(280, 220, 93, 28))
        self.btnCreate.setObjectName("btnCreate")
        self.btnCancel = QtWidgets.QPushButton(CreateLayerDialog)
        self.btnCancel.setGeometry(QtCore.QRect(390, 220, 93, 28))
        self.btnCancel.setObjectName("btnCancel")
        self.txtMapName = QtWidgets.QLineEdit(CreateLayerDialog)
        self.txtMapName.setGeometry(QtCore.QRect(140, 130, 331, 21))
        self.txtMapName.setStyleSheet("background-color: #fff79a")
        self.txtMapName.setObjectName("txtMapName")
        self.lblGroupName = QtWidgets.QLabel(CreateLayerDialog)
        self.lblGroupName.setGeometry(QtCore.QRect(10, 130, 131, 21))
        self.lblGroupName.setObjectName("lblGroupName")
        self.lblLayerType = QtWidgets.QLabel(CreateLayerDialog)
        self.lblLayerType.setGeometry(QtCore.QRect(10, 30, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblLayerType.setFont(font)
        self.lblLayerType.setObjectName("lblLayerType")
        self.cboLayerType = QtWidgets.QComboBox(CreateLayerDialog)
        self.cboLayerType.setGeometry(QtCore.QRect(140, 30, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.cboLayerType.setFont(font)
        self.cboLayerType.setCurrentText("")
        self.cboLayerType.setObjectName("cboLayerType")
        self.lblFileName2 = QtWidgets.QLabel(CreateLayerDialog)
        self.lblFileName2.setGeometry(QtCore.QRect(270, 160, 201, 21))
        self.lblFileName2.setObjectName("lblFileName2")
        self.cboMapType = QtWidgets.QComboBox(CreateLayerDialog)
        self.cboMapType.setGeometry(QtCore.QRect(140, 60, 271, 22))
        self.cboMapType.setObjectName("cboMapType")
        self.label = QtWidgets.QLabel(CreateLayerDialog)
        self.label.setGeometry(QtCore.QRect(10, 60, 131, 21))
        self.label.setObjectName("label")
        self.frmFileSelect = QtWidgets.QFrame(CreateLayerDialog)
        self.frmFileSelect.setGeometry(QtCore.QRect(0, 80, 481, 41))
        self.frmFileSelect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFileSelect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFileSelect.setObjectName("frmFileSelect")
        self.btnFileSelect = QtWidgets.QPushButton(self.frmFileSelect)
        self.btnFileSelect.setGeometry(QtCore.QRect(420, 10, 51, 23))
        self.btnFileSelect.setObjectName("btnFileSelect")
        self.txtFileSelect = QtWidgets.QLineEdit(self.frmFileSelect)
        self.txtFileSelect.setGeometry(QtCore.QRect(140, 10, 271, 20))
        self.txtFileSelect.setStyleSheet("background-color: #fff79a")
        self.txtFileSelect.setObjectName("txtFileSelect")
        self.txtUrl = QtWidgets.QLineEdit(self.frmFileSelect)
        self.txtUrl.setGeometry(QtCore.QRect(140, 10, 331, 22))
        self.txtUrl.setStyleSheet("background-color: #fff79a")
        self.txtUrl.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.txtUrl.setObjectName("txtUrl")
        self.lblFile = QtWidgets.QLabel(CreateLayerDialog)
        self.lblFile.setGeometry(QtCore.QRect(10, 90, 121, 21))
        self.lblFile.setText("")
        self.lblFile.setObjectName("lblFile")
        self.frmFileSelect.raise_()
        self.lblFileName.raise_()
        self.txtFileName.raise_()
        self.btnCreate.raise_()
        self.btnCancel.raise_()
        self.txtMapName.raise_()
        self.lblGroupName.raise_()
        self.lblLayerType.raise_()
        self.cboLayerType.raise_()
        self.lblFileName2.raise_()
        self.cboMapType.raise_()
        self.label.raise_()
        self.lblFile.raise_()

        self.retranslateUi(CreateLayerDialog)
        self.cboLayerType.currentTextChanged['QString'].connect(self.cboMapType.setEditText)
        QtCore.QMetaObject.connectSlotsByName(CreateLayerDialog)
        CreateLayerDialog.setTabOrder(self.cboLayerType, self.cboMapType)
        CreateLayerDialog.setTabOrder(self.cboMapType, self.txtFileSelect)
        CreateLayerDialog.setTabOrder(self.txtFileSelect, self.btnFileSelect)
        CreateLayerDialog.setTabOrder(self.btnFileSelect, self.txtMapName)
        CreateLayerDialog.setTabOrder(self.txtMapName, self.txtFileName)
        CreateLayerDialog.setTabOrder(self.txtFileName, self.btnCreate)
        CreateLayerDialog.setTabOrder(self.btnCreate, self.btnCancel)

    def retranslateUi(self, CreateLayerDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateLayerDialog.setWindowTitle(_translate("CreateLayerDialog", "Create Layer"))
        self.lblFileName.setText(_translate("CreateLayerDialog", "File Name"))
        self.txtFileName.setPlaceholderText(_translate("CreateLayerDialog", "e.g. scenario01"))
        self.btnCreate.setText(_translate("CreateLayerDialog", "Create"))
        self.btnCancel.setText(_translate("CreateLayerDialog", "Cancel"))
        self.txtMapName.setPlaceholderText(_translate("CreateLayerDialog", "e.g. 1. Major geosites"))
        self.lblGroupName.setText(_translate("CreateLayerDialog", "Map Name"))
        self.lblLayerType.setText(_translate("CreateLayerDialog", "Select Layer Type"))
        self.lblFileName2.setText(_translate("CreateLayerDialog", " (single-byte character only)"))
        self.label.setText(_translate("CreateLayerDialog", "Select Map Type"))
        self.btnFileSelect.setText(_translate("CreateLayerDialog", "Select"))
        self.txtUrl.setPlaceholderText(_translate("CreateLayerDialog", "e.g. https://gbank.gsj.jp/ows/seamlessgeology200k_d"))

