# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_export_to_geolib_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExportToGeolibDialog(object):
    def setupUi(self, ExportToGeolibDialog):
        ExportToGeolibDialog.setObjectName("ExportToGeolibDialog")
        ExportToGeolibDialog.resize(934, 649)
        self.btnClose = QtWidgets.QPushButton(ExportToGeolibDialog)
        self.btnClose.setGeometry(QtCore.QRect(820, 590, 93, 31))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnClose.setObjectName("btnClose")
        self.lblConnectMessage = QtWidgets.QLabel(ExportToGeolibDialog)
        self.lblConnectMessage.setGeometry(QtCore.QRect(180, 20, 721, 21))
        self.lblConnectMessage.setWordWrap(True)
        self.lblConnectMessage.setObjectName("lblConnectMessage")
        self.lblMessage = QtWidgets.QLabel(ExportToGeolibDialog)
        self.lblMessage.setGeometry(QtCore.QRect(40, 55, 421, 21))
        self.lblMessage.setWordWrap(True)
        self.lblMessage.setObjectName("lblMessage")
        self.btnConnect = QtWidgets.QPushButton(ExportToGeolibDialog)
        self.btnConnect.setGeometry(QtCore.QRect(30, 20, 141, 28))
        self.btnConnect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnConnect.setObjectName("btnConnect")
        self.tblArticles = QtWidgets.QTableView(ExportToGeolibDialog)
        self.tblArticles.setGeometry(QtCore.QRect(30, 80, 430, 150))
        self.tblArticles.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tblArticles.setObjectName("tblArticles")
        self.btnNew = QtWidgets.QPushButton(ExportToGeolibDialog)
        self.btnNew.setGeometry(QtCore.QRect(30, 240, 211, 28))
        self.btnNew.setObjectName("btnNew")
        self.btnEdit = QtWidgets.QPushButton(ExportToGeolibDialog)
        self.btnEdit.setEnabled(True)
        self.btnEdit.setGeometry(QtCore.QRect(250, 240, 211, 28))
        self.btnEdit.setObjectName("btnEdit")
        self.grpArticle = QtWidgets.QGroupBox(ExportToGeolibDialog)
        self.grpArticle.setGeometry(QtCore.QRect(20, 280, 441, 341))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grpArticle.setFont(font)
        self.grpArticle.setObjectName("grpArticle")
        self.lblUpdateDate = QtWidgets.QLabel(self.grpArticle)
        self.lblUpdateDate.setGeometry(QtCore.QRect(20, 270, 91, 21))
        self.lblUpdateDate.setObjectName("lblUpdateDate")
        self.lblModifiedDate = QtWidgets.QLabel(self.grpArticle)
        self.lblModifiedDate.setGeometry(QtCore.QRect(120, 270, 131, 21))
        self.lblModifiedDate.setObjectName("lblModifiedDate")
        self.lblCreateDate_2 = QtWidgets.QLabel(self.grpArticle)
        self.lblCreateDate_2.setGeometry(QtCore.QRect(20, 250, 91, 21))
        self.lblCreateDate_2.setObjectName("lblCreateDate_2")
        self.lblCreateDate = QtWidgets.QLabel(self.grpArticle)
        self.lblCreateDate.setGeometry(QtCore.QRect(120, 250, 131, 21))
        self.lblCreateDate.setObjectName("lblCreateDate")
        self.chkPublished = QtWidgets.QCheckBox(self.grpArticle)
        self.chkPublished.setGeometry(QtCore.QRect(120, 90, 151, 21))
        self.chkPublished.setObjectName("chkPublished")
        self.txtAbstract = QtWidgets.QTextEdit(self.grpArticle)
        self.txtAbstract.setGeometry(QtCore.QRect(120, 180, 301, 61))
        self.txtAbstract.setObjectName("txtAbstract")
        self.lblAbstract = QtWidgets.QLabel(self.grpArticle)
        self.lblAbstract.setGeometry(QtCore.QRect(20, 180, 91, 71))
        self.lblAbstract.setObjectName("lblAbstract")
        self.lblLevel = QtWidgets.QLabel(self.grpArticle)
        self.lblLevel.setGeometry(QtCore.QRect(20, 151, 91, 20))
        self.lblLevel.setObjectName("lblLevel")
        self.cboLevel = QtWidgets.QComboBox(self.grpArticle)
        self.cboLevel.setGeometry(QtCore.QRect(120, 150, 231, 21))
        self.cboLevel.setObjectName("cboLevel")
        self.lblArea = QtWidgets.QLabel(self.grpArticle)
        self.lblArea.setGeometry(QtCore.QRect(20, 120, 91, 21))
        self.lblArea.setObjectName("lblArea")
        self.cboArea = QtWidgets.QComboBox(self.grpArticle)
        self.cboArea.setGeometry(QtCore.QRect(120, 120, 231, 21))
        self.cboArea.setObjectName("cboArea")
        self.txtTitle = QtWidgets.QLineEdit(self.grpArticle)
        self.txtTitle.setGeometry(QtCore.QRect(120, 60, 301, 21))
        self.txtTitle.setStyleSheet("background-color: #fff79a")
        self.txtTitle.setObjectName("txtTitle")
        self.txtName = QtWidgets.QLineEdit(self.grpArticle)
        self.txtName.setGeometry(QtCore.QRect(120, 30, 301, 21))
        self.txtName.setStyleSheet("background-color: #fff79a")
        self.txtName.setObjectName("txtName")
        self.lblName = QtWidgets.QLabel(self.grpArticle)
        self.lblName.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.lblName.setObjectName("lblName")
        self.lblTitle = QtWidgets.QLabel(self.grpArticle)
        self.lblTitle.setGeometry(QtCore.QRect(20, 60, 81, 21))
        self.lblTitle.setObjectName("lblTitle")
        self.btnSave = QtWidgets.QPushButton(self.grpArticle)
        self.btnSave.setGeometry(QtCore.QRect(270, 260, 151, 31))
        self.btnSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSave.setObjectName("btnSave")
        self.btnDelete = QtWidgets.QPushButton(self.grpArticle)
        self.btnDelete.setGeometry(QtCore.QRect(10, 300, 91, 31))
        self.btnDelete.setObjectName("btnDelete")
        self.grpMapData = QtWidgets.QGroupBox(ExportToGeolibDialog)
        self.grpMapData.setGeometry(QtCore.QRect(470, 50, 441, 531))
        font = QtGui.QFont()
        font.setItalic(False)
        self.grpMapData.setFont(font)
        self.grpMapData.setObjectName("grpMapData")
        self.chkSymbolIcons = QtWidgets.QCheckBox(self.grpMapData)
        self.chkSymbolIcons.setGeometry(QtCore.QRect(300, 20, 131, 20))
        self.chkSymbolIcons.setObjectName("chkSymbolIcons")
        self.lblSymbolIcons = QtWidgets.QLabel(self.grpMapData)
        self.lblSymbolIcons.setGeometry(QtCore.QRect(20, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSymbolIcons.setFont(font)
        self.lblSymbolIcons.setObjectName("lblSymbolIcons")
        self.tblScenarioMap = QtWidgets.QTableView(self.grpMapData)
        self.tblScenarioMap.setGeometry(QtCore.QRect(20, 170, 400, 100))
        self.tblScenarioMap.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tblScenarioMap.setAlternatingRowColors(True)
        self.tblScenarioMap.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblScenarioMap.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblScenarioMap.setObjectName("tblScenarioMap")
        self.lblScenarioMap = QtWidgets.QLabel(self.grpMapData)
        self.lblScenarioMap.setGeometry(QtCore.QRect(20, 150, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblScenarioMap.setFont(font)
        self.lblScenarioMap.setObjectName("lblScenarioMap")
        self.tblSubjectMap = QtWidgets.QTableView(self.grpMapData)
        self.tblSubjectMap.setGeometry(QtCore.QRect(20, 300, 400, 100))
        self.tblSubjectMap.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tblSubjectMap.setAlternatingRowColors(True)
        self.tblSubjectMap.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblSubjectMap.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblSubjectMap.setObjectName("tblSubjectMap")
        self.lblScenarioFiles = QtWidgets.QLabel(self.grpMapData)
        self.lblScenarioFiles.setGeometry(QtCore.QRect(20, 50, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblScenarioFiles.setFont(font)
        self.lblScenarioFiles.setObjectName("lblScenarioFiles")
        self.chkScenarioFiles = QtWidgets.QCheckBox(self.grpMapData)
        self.chkScenarioFiles.setGeometry(QtCore.QRect(300, 50, 131, 16))
        self.chkScenarioFiles.setObjectName("chkScenarioFiles")
        self.lblSubjectMap = QtWidgets.QLabel(self.grpMapData)
        self.lblSubjectMap.setGeometry(QtCore.QRect(20, 280, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSubjectMap.setFont(font)
        self.lblSubjectMap.setTextFormat(QtCore.Qt.RichText)
        self.lblSubjectMap.setObjectName("lblSubjectMap")
        self.btnUpload = QtWidgets.QPushButton(self.grpMapData)
        self.btnUpload.setGeometry(QtCore.QRect(240, 80, 191, 31))
        self.btnUpload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUpload.setObjectName("btnUpload")
        self.lblSymbolMessage = QtWidgets.QLabel(self.grpMapData)
        self.lblSymbolMessage.setGeometry(QtCore.QRect(110, 20, 191, 16))
        self.lblSymbolMessage.setObjectName("lblSymbolMessage")
        self.lblScenarioMessage = QtWidgets.QLabel(self.grpMapData)
        self.lblScenarioMessage.setGeometry(QtCore.QRect(110, 50, 191, 16))
        self.lblScenarioMessage.setObjectName("lblScenarioMessage")
        self.lblAssociatedMap = QtWidgets.QLabel(self.grpMapData)
        self.lblAssociatedMap.setGeometry(QtCore.QRect(20, 410, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAssociatedMap.setFont(font)
        self.lblAssociatedMap.setTextFormat(QtCore.Qt.RichText)
        self.lblAssociatedMap.setObjectName("lblAssociatedMap")
        self.tblAssociatedMap = QtWidgets.QTableView(self.grpMapData)
        self.tblAssociatedMap.setGeometry(QtCore.QRect(20, 430, 400, 90))
        self.tblAssociatedMap.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tblAssociatedMap.setAlternatingRowColors(True)
        self.tblAssociatedMap.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblAssociatedMap.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAssociatedMap.setObjectName("tblAssociatedMap")
        self.btnNewMap = QtWidgets.QPushButton(self.grpMapData)
        self.btnNewMap.setGeometry(QtCore.QRect(20, 110, 131, 31))
        self.btnNewMap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNewMap.setObjectName("btnNewMap")
        self.label = QtWidgets.QLabel(self.grpMapData)
        self.label.setGeometry(QtCore.QRect(190, 130, 171, 21))
        self.label.setObjectName("label")
        self.wgtExportMap = QtWidgets.QDockWidget(ExportToGeolibDialog)
        self.wgtExportMap.setGeometry(QtCore.QRect(200, 250, 601, 251))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.wgtExportMap.setPalette(palette)
        self.wgtExportMap.setAutoFillBackground(True)
        self.wgtExportMap.setStyleSheet("")
        self.wgtExportMap.setFloating(True)
        self.wgtExportMap.setObjectName("wgtExportMap")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setAutoFillBackground(True)
        self.dockWidgetContents.setStyleSheet("")
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.cboMapType = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cboMapType.setGeometry(QtCore.QRect(170, 10, 201, 22))
        self.cboMapType.setObjectName("cboMapType")
        self.cboMapType.addItem("")
        self.cboMapType.addItem("")
        self.cboMapType.addItem("")
        self.lblMapTitle = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblMapTitle.setGeometry(QtCore.QRect(50, 40, 111, 20))
        self.lblMapTitle.setObjectName("lblMapTitle")
        self.txtMapTitle = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.txtMapTitle.setGeometry(QtCore.QRect(170, 40, 361, 20))
        self.txtMapTitle.setStyleSheet("background-color: #fff79a")
        self.txtMapTitle.setMaxLength(200)
        self.txtMapTitle.setFrame(True)
        self.txtMapTitle.setClearButtonEnabled(False)
        self.txtMapTitle.setObjectName("txtMapTitle")
        self.lblMapType = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblMapType.setGeometry(QtCore.QRect(50, 11, 111, 20))
        self.lblMapType.setObjectName("lblMapType")
        self.btnMapSave = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnMapSave.setGeometry(QtCore.QRect(400, 180, 81, 31))
        self.btnMapSave.setObjectName("btnMapSave")
        self.btnMapCancel = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnMapCancel.setGeometry(QtCore.QRect(500, 180, 81, 31))
        self.btnMapCancel.setObjectName("btnMapCancel")
        self.frmAssociated = QtWidgets.QFrame(self.dockWidgetContents)
        self.frmAssociated.setGeometry(QtCore.QRect(30, 60, 561, 111))
        self.frmAssociated.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmAssociated.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmAssociated.setObjectName("frmAssociated")
        self.txtAttribution = QtWidgets.QLineEdit(self.frmAssociated)
        self.txtAttribution.setGeometry(QtCore.QRect(140, 80, 411, 20))
        self.txtAttribution.setObjectName("txtAttribution")
        self.lblAttribution = QtWidgets.QLabel(self.frmAssociated)
        self.lblAttribution.setGeometry(QtCore.QRect(20, 80, 111, 20))
        self.lblAttribution.setObjectName("lblAttribution")
        self.txtScript = QtWidgets.QTextEdit(self.frmAssociated)
        self.txtScript.setGeometry(QtCore.QRect(140, 10, 411, 61))
        self.txtScript.setObjectName("txtScript")
        self.lblScript = QtWidgets.QLabel(self.frmAssociated)
        self.lblScript.setGeometry(QtCore.QRect(20, 10, 111, 20))
        self.lblScript.setObjectName("lblScript")
        self.frmScenario = QtWidgets.QFrame(self.dockWidgetContents)
        self.frmScenario.setGeometry(QtCore.QRect(30, 70, 561, 80))
        self.frmScenario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmScenario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmScenario.setObjectName("frmScenario")
        self.cboSourceType = QtWidgets.QComboBox(self.frmScenario)
        self.cboSourceType.setGeometry(QtCore.QRect(140, 10, 201, 22))
        self.cboSourceType.setObjectName("cboSourceType")
        self.cboSourceType.addItem("")
        self.cboSourceType.addItem("")
        self.lblSourceType = QtWidgets.QLabel(self.frmScenario)
        self.lblSourceType.setGeometry(QtCore.QRect(20, 10, 111, 20))
        self.lblSourceType.setObjectName("lblSourceType")
        self.cboLayerData = QtWidgets.QComboBox(self.frmScenario)
        self.cboLayerData.setGeometry(QtCore.QRect(350, 40, 201, 22))
        self.cboLayerData.setObjectName("cboLayerData")
        self.lblLayerData = QtWidgets.QLabel(self.frmScenario)
        self.lblLayerData.setGeometry(QtCore.QRect(20, 40, 111, 20))
        self.lblLayerData.setObjectName("lblLayerData")
        self.txtFolderName = QtWidgets.QLineEdit(self.frmScenario)
        self.txtFolderName.setGeometry(QtCore.QRect(140, 40, 201, 20))
        self.txtFolderName.setStyleSheet("background-color: #fff79a")
        self.txtFolderName.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.txtFolderName.setObjectName("txtFolderName")
        self.btnMapDelete = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnMapDelete.setGeometry(QtCore.QRect(30, 182, 81, 31))
        self.btnMapDelete.setObjectName("btnMapDelete")
        self.lblMapType.raise_()
        self.lblMapTitle.raise_()
        self.txtMapTitle.raise_()
        self.btnMapCancel.raise_()
        self.cboMapType.raise_()
        self.btnMapSave.raise_()
        self.frmAssociated.raise_()
        self.frmScenario.raise_()
        self.btnMapDelete.raise_()
        self.wgtExportMap.setWidget(self.dockWidgetContents)
        self.grpMapData.raise_()
        self.grpArticle.raise_()
        self.btnClose.raise_()
        self.lblConnectMessage.raise_()
        self.lblMessage.raise_()
        self.btnConnect.raise_()
        self.tblArticles.raise_()
        self.btnNew.raise_()
        self.btnEdit.raise_()
        self.wgtExportMap.raise_()

        self.retranslateUi(ExportToGeolibDialog)
        QtCore.QMetaObject.connectSlotsByName(ExportToGeolibDialog)
        ExportToGeolibDialog.setTabOrder(self.btnConnect, self.tblArticles)
        ExportToGeolibDialog.setTabOrder(self.tblArticles, self.btnEdit)
        ExportToGeolibDialog.setTabOrder(self.btnEdit, self.btnNew)
        ExportToGeolibDialog.setTabOrder(self.btnNew, self.txtName)
        ExportToGeolibDialog.setTabOrder(self.txtName, self.txtTitle)
        ExportToGeolibDialog.setTabOrder(self.txtTitle, self.chkPublished)
        ExportToGeolibDialog.setTabOrder(self.chkPublished, self.cboArea)
        ExportToGeolibDialog.setTabOrder(self.cboArea, self.cboLevel)
        ExportToGeolibDialog.setTabOrder(self.cboLevel, self.txtAbstract)
        ExportToGeolibDialog.setTabOrder(self.txtAbstract, self.btnSave)
        ExportToGeolibDialog.setTabOrder(self.btnSave, self.chkSymbolIcons)
        ExportToGeolibDialog.setTabOrder(self.chkSymbolIcons, self.chkScenarioFiles)
        ExportToGeolibDialog.setTabOrder(self.chkScenarioFiles, self.btnUpload)
        ExportToGeolibDialog.setTabOrder(self.btnUpload, self.tblScenarioMap)
        ExportToGeolibDialog.setTabOrder(self.tblScenarioMap, self.tblSubjectMap)
        ExportToGeolibDialog.setTabOrder(self.tblSubjectMap, self.tblAssociatedMap)
        ExportToGeolibDialog.setTabOrder(self.tblAssociatedMap, self.cboMapType)
        ExportToGeolibDialog.setTabOrder(self.cboMapType, self.txtMapTitle)
        ExportToGeolibDialog.setTabOrder(self.txtMapTitle, self.cboSourceType)
        ExportToGeolibDialog.setTabOrder(self.cboSourceType, self.txtFolderName)
        ExportToGeolibDialog.setTabOrder(self.txtFolderName, self.cboLayerData)
        ExportToGeolibDialog.setTabOrder(self.cboLayerData, self.txtScript)
        ExportToGeolibDialog.setTabOrder(self.txtScript, self.txtAttribution)
        ExportToGeolibDialog.setTabOrder(self.txtAttribution, self.btnMapSave)
        ExportToGeolibDialog.setTabOrder(self.btnMapSave, self.btnMapCancel)
        ExportToGeolibDialog.setTabOrder(self.btnMapCancel, self.btnClose)

    def retranslateUi(self, ExportToGeolibDialog):
        _translate = QtCore.QCoreApplication.translate
        ExportToGeolibDialog.setWindowTitle(_translate("ExportToGeolibDialog", "Export Layer Data to Geolib"))
        self.btnClose.setText(_translate("ExportToGeolibDialog", "Close"))
        self.lblConnectMessage.setText(_translate("ExportToGeolibDialog", "Please click the [Connect] button to connect to the server."))
        self.lblMessage.setText(_translate("ExportToGeolibDialog", "List of already registered libraries is displayed."))
        self.btnConnect.setText(_translate("ExportToGeolibDialog", "Connect"))
        self.btnNew.setText(_translate("ExportToGeolibDialog", "New Article"))
        self.btnEdit.setText(_translate("ExportToGeolibDialog", "Edit Article"))
        self.grpArticle.setTitle(_translate("ExportToGeolibDialog", "Article"))
        self.lblUpdateDate.setText(_translate("ExportToGeolibDialog", "Update Date"))
        self.lblModifiedDate.setText(_translate("ExportToGeolibDialog", "1999/01/01"))
        self.lblCreateDate_2.setText(_translate("ExportToGeolibDialog", "Create Date"))
        self.lblCreateDate.setText(_translate("ExportToGeolibDialog", "1999/01/01"))
        self.chkPublished.setText(_translate("ExportToGeolibDialog", "Published"))
        self.lblAbstract.setText(_translate("ExportToGeolibDialog", "Abstract"))
        self.lblLevel.setText(_translate("ExportToGeolibDialog", "Level"))
        self.lblArea.setText(_translate("ExportToGeolibDialog", "Area"))
        self.txtTitle.setPlaceholderText(_translate("ExportToGeolibDialog", "e.g. Geological Map for  my town"))
        self.txtName.setPlaceholderText(_translate("ExportToGeolibDialog", "e.g. My town map"))
        self.lblName.setText(_translate("ExportToGeolibDialog", "Name"))
        self.lblTitle.setText(_translate("ExportToGeolibDialog", "Title"))
        self.btnSave.setText(_translate("ExportToGeolibDialog", "Save"))
        self.btnDelete.setText(_translate("ExportToGeolibDialog", "Delete"))
        self.grpMapData.setTitle(_translate("ExportToGeolibDialog", "Map Data"))
        self.chkSymbolIcons.setText(_translate("ExportToGeolibDialog", "Export and Replace"))
        self.lblSymbolIcons.setText(_translate("ExportToGeolibDialog", "Symbol Icons:"))
        self.lblScenarioMap.setText(_translate("ExportToGeolibDialog", "Scenario Map"))
        self.lblScenarioFiles.setText(_translate("ExportToGeolibDialog", "Scenario Files:"))
        self.chkScenarioFiles.setText(_translate("ExportToGeolibDialog", "Export and Replace"))
        self.lblSubjectMap.setText(_translate("ExportToGeolibDialog", "Subject Map"))
        self.btnUpload.setText(_translate("ExportToGeolibDialog", "Upload checked files"))
        self.lblSymbolMessage.setText(_translate("ExportToGeolibDialog", "There is no file."))
        self.lblScenarioMessage.setText(_translate("ExportToGeolibDialog", "There is no file."))
        self.lblAssociatedMap.setText(_translate("ExportToGeolibDialog", "Associated Map"))
        self.btnNewMap.setText(_translate("ExportToGeolibDialog", "New Map Regist"))
        self.label.setText(_translate("ExportToGeolibDialog", "Double-click a line to edit it"))
        self.wgtExportMap.setWindowTitle(_translate("ExportToGeolibDialog", "Export Map"))
        self.cboMapType.setItemText(0, _translate("ExportToGeolibDialog", "Scenario"))
        self.cboMapType.setItemText(1, _translate("ExportToGeolibDialog", "Subject"))
        self.cboMapType.setItemText(2, _translate("ExportToGeolibDialog", "Associated"))
        self.lblMapTitle.setText(_translate("ExportToGeolibDialog", "Title"))
        self.txtMapTitle.setPlaceholderText(_translate("ExportToGeolibDialog", "e.g. Observation point"))
        self.lblMapType.setText(_translate("ExportToGeolibDialog", "Map Type"))
        self.btnMapSave.setText(_translate("ExportToGeolibDialog", "Save"))
        self.btnMapCancel.setText(_translate("ExportToGeolibDialog", "Cancel"))
        self.lblAttribution.setText(_translate("ExportToGeolibDialog", "Attribution"))
        self.lblScript.setText(_translate("ExportToGeolibDialog", "Script"))
        self.cboSourceType.setItemText(0, _translate("ExportToGeolibDialog", "GeoJSON"))
        self.cboSourceType.setItemText(1, _translate("ExportToGeolibDialog", "geoTIFF"))
        self.lblSourceType.setText(_translate("ExportToGeolibDialog", "Source Type"))
        self.lblLayerData.setText(_translate("ExportToGeolibDialog", "Layer Data"))
        self.txtFolderName.setPlaceholderText(_translate("ExportToGeolibDialog", "e.g. Folder_A"))
        self.btnMapDelete.setText(_translate("ExportToGeolibDialog", "Delete"))

