# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_edit_attribute_dockwidget.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditAttributeDockWidget(object):
    def setupUi(self, EditAttributeDockWidget):
        EditAttributeDockWidget.setObjectName("EditAttributeDockWidget")
        EditAttributeDockWidget.setEnabled(True)
        EditAttributeDockWidget.resize(290, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditAttributeDockWidget.sizePolicy().hasHeightForWidth())
        EditAttributeDockWidget.setSizePolicy(sizePolicy)
        EditAttributeDockWidget.setMinimumSize(QtCore.QSize(290, 400))
        EditAttributeDockWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        EditAttributeDockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.frmScenario = QtWidgets.QFrame(self.dockWidgetContents)
        self.frmScenario.setGeometry(QtCore.QRect(10, 190, 281, 71))
        self.frmScenario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmScenario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmScenario.setObjectName("frmScenario")
        self.btnFileSelect = QtWidgets.QPushButton(self.frmScenario)
        self.btnFileSelect.setGeometry(QtCore.QRect(240, 10, 31, 21))
        self.btnFileSelect.setObjectName("btnFileSelect")
        self.txtFilename = QtWidgets.QLineEdit(self.frmScenario)
        self.txtFilename.setGeometry(QtCore.QRect(70, 10, 171, 21))
        self.txtFilename.setObjectName("txtFilename")
        self.lblFileName = QtWidgets.QLabel(self.frmScenario)
        self.lblFileName.setGeometry(QtCore.QRect(0, 10, 71, 21))
        self.lblFileName.setObjectName("lblFileName")
        self.btnPreview = QtWidgets.QPushButton(self.frmScenario)
        self.btnPreview.setGeometry(QtCore.QRect(70, 40, 81, 23))
        self.btnPreview.setObjectName("btnPreview")
        self.txtDescription = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.txtDescription.setGeometry(QtCore.QRect(100, 120, 181, 71))
        self.txtDescription.setObjectName("txtDescription")
        self.grpStyle = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.grpStyle.setGeometry(QtCore.QRect(10, 40, 281, 51))
        self.grpStyle.setObjectName("grpStyle")
        self.cboSymbol = QtWidgets.QComboBox(self.grpStyle)
        self.cboSymbol.setGeometry(QtCore.QRect(70, 20, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.cboSymbol.setFont(font)
        self.cboSymbol.setObjectName("cboSymbol")
        self.lblSymbol = QtWidgets.QLabel(self.grpStyle)
        self.lblSymbol.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.lblSymbol.setObjectName("lblSymbol")
        self.frmStrDip = QtWidgets.QFrame(self.dockWidgetContents)
        self.frmStrDip.setGeometry(QtCore.QRect(10, 190, 281, 91))
        self.frmStrDip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmStrDip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmStrDip.setObjectName("frmStrDip")
        self.cboStrike2 = QtWidgets.QComboBox(self.frmStrDip)
        self.cboStrike2.setGeometry(QtCore.QRect(200, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cboStrike2.setFont(font)
        self.cboStrike2.setObjectName("cboStrike2")
        self.cboStrike2.addItem("")
        self.cboStrike2.addItem("")
        self.cboStrike2.addItem("")
        self.spnStrike = QtWidgets.QDoubleSpinBox(self.frmStrDip)
        self.spnStrike.setGeometry(QtCore.QRect(130, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spnStrike.setFont(font)
        self.spnStrike.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnStrike.setDecimals(0)
        self.spnStrike.setMaximum(90.0)
        self.spnStrike.setObjectName("spnStrike")
        self.lblStrike = QtWidgets.QLabel(self.frmStrDip)
        self.lblStrike.setGeometry(QtCore.QRect(0, 10, 71, 21))
        self.lblStrike.setObjectName("lblStrike")
        self.lblDip = QtWidgets.QLabel(self.frmStrDip)
        self.lblDip.setGeometry(QtCore.QRect(0, 50, 61, 21))
        self.lblDip.setObjectName("lblDip")
        self.spnDip = QtWidgets.QDoubleSpinBox(self.frmStrDip)
        self.spnDip.setGeometry(QtCore.QRect(130, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.spnDip.setFont(font)
        self.spnDip.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spnDip.setDecimals(0)
        self.spnDip.setMaximum(90.0)
        self.spnDip.setObjectName("spnDip")
        self.cboStrike1 = QtWidgets.QComboBox(self.frmStrDip)
        self.cboStrike1.setGeometry(QtCore.QRect(70, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cboStrike1.setFont(font)
        self.cboStrike1.setObjectName("cboStrike1")
        self.cboStrike1.addItem("")
        self.cboDip = QtWidgets.QComboBox(self.frmStrDip)
        self.cboDip.setGeometry(QtCore.QRect(200, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cboDip.setFont(font)
        self.cboDip.setObjectName("cboDip")
        self.cboDip.addItem("")
        self.cboDip.addItem("")
        self.cboDip.addItem("")
        self.cboDip.addItem("")
        self.btnUpdate = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnUpdate.setGeometry(QtCore.QRect(190, 340, 93, 31))
        self.btnUpdate.setObjectName("btnUpdate")
        self.txtLegend01 = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.txtLegend01.setGeometry(QtCore.QRect(100, 90, 181, 21))
        self.txtLegend01.setObjectName("txtLegend01")
        self.lblDescription = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblDescription.setGeometry(QtCore.QRect(10, 120, 91, 71))
        self.lblDescription.setObjectName("lblDescription")
        self.lblLegend01 = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblLegend01.setGeometry(QtCore.QRect(10, 90, 91, 20))
        self.lblLegend01.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend01.setObjectName("lblLegend01")
        self.frmLegend = QtWidgets.QFrame(self.dockWidgetContents)
        self.frmLegend.setGeometry(QtCore.QRect(10, 190, 281, 141))
        self.frmLegend.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmLegend.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmLegend.setObjectName("frmLegend")
        self.txtLegend02 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend02.setGeometry(QtCore.QRect(100, 10, 171, 21))
        self.txtLegend02.setObjectName("txtLegend02")
        self.txtLegend06 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend06.setGeometry(QtCore.QRect(100, 90, 171, 21))
        self.txtLegend06.setObjectName("txtLegend06")
        self.lblLegend07 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend07.setGeometry(QtCore.QRect(0, 111, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend07.setFont(font)
        self.lblLegend07.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend07.setObjectName("lblLegend07")
        self.lblLegend06 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend06.setGeometry(QtCore.QRect(0, 91, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend06.setFont(font)
        self.lblLegend06.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend06.setObjectName("lblLegend06")
        self.txtLegend03 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend03.setGeometry(QtCore.QRect(100, 30, 171, 21))
        self.txtLegend03.setObjectName("txtLegend03")
        self.lblLegend03 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend03.setGeometry(QtCore.QRect(0, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend03.setFont(font)
        self.lblLegend03.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend03.setObjectName("lblLegend03")
        self.txtLegend05 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend05.setGeometry(QtCore.QRect(100, 70, 171, 21))
        self.txtLegend05.setObjectName("txtLegend05")
        self.lblLegend02 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend02.setGeometry(QtCore.QRect(0, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend02.setFont(font)
        self.lblLegend02.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend02.setObjectName("lblLegend02")
        self.lblLegend04 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend04.setGeometry(QtCore.QRect(0, 51, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend04.setFont(font)
        self.lblLegend04.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend04.setObjectName("lblLegend04")
        self.txtLegend07 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend07.setGeometry(QtCore.QRect(100, 110, 171, 21))
        self.txtLegend07.setObjectName("txtLegend07")
        self.txtLegend04 = QtWidgets.QLineEdit(self.frmLegend)
        self.txtLegend04.setGeometry(QtCore.QRect(100, 50, 171, 21))
        self.txtLegend04.setObjectName("txtLegend04")
        self.lblLegend05 = QtWidgets.QLabel(self.frmLegend)
        self.lblLegend05.setGeometry(QtCore.QRect(0, 71, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblLegend05.setFont(font)
        self.lblLegend05.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblLegend05.setObjectName("lblLegend05")
        self.txtLayerName = QtWidgets.QLabel(self.dockWidgetContents)
        self.txtLayerName.setGeometry(QtCore.QRect(80, 0, 211, 21))
        self.txtLayerName.setText("")
        self.txtLayerName.setObjectName("txtLayerName")
        self.txtFeature = QtWidgets.QLabel(self.dockWidgetContents)
        self.txtFeature.setGeometry(QtCore.QRect(130, 20, 131, 20))
        self.txtFeature.setText("")
        self.txtFeature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtFeature.setObjectName("txtFeature")
        self.lblLayerName = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblLayerName.setGeometry(QtCore.QRect(10, 0, 71, 21))
        self.lblLayerName.setObjectName("lblLayerName")
        self.lblFeature = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblFeature.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.lblFeature.setObjectName("lblFeature")
        self.btnSelectCancel = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnSelectCancel.setGeometry(QtCore.QRect(10, 340, 91, 31))
        self.btnSelectCancel.setObjectName("btnSelectCancel")
        EditAttributeDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(EditAttributeDockWidget)
        QtCore.QMetaObject.connectSlotsByName(EditAttributeDockWidget)

    def retranslateUi(self, EditAttributeDockWidget):
        _translate = QtCore.QCoreApplication.translate
        EditAttributeDockWidget.setWindowTitle(_translate("EditAttributeDockWidget", "Edit Feature Attribute"))
        self.btnFileSelect.setText(_translate("EditAttributeDockWidget", "..."))
        self.lblFileName.setText(_translate("EditAttributeDockWidget", "Filename"))
        self.btnPreview.setText(_translate("EditAttributeDockWidget", "Preview"))
        self.grpStyle.setTitle(_translate("EditAttributeDockWidget", "Style"))
        self.lblSymbol.setText(_translate("EditAttributeDockWidget", "Symbol"))
        self.cboStrike2.setItemText(0, _translate("EditAttributeDockWidget", "E"))
        self.cboStrike2.setItemText(1, _translate("EditAttributeDockWidget", "W"))
        self.cboStrike2.setItemText(2, _translate("EditAttributeDockWidget", "S"))
        self.lblStrike.setText(_translate("EditAttributeDockWidget", "Strike"))
        self.lblDip.setText(_translate("EditAttributeDockWidget", "Dip"))
        self.cboStrike1.setItemText(0, _translate("EditAttributeDockWidget", "N"))
        self.cboDip.setItemText(0, _translate("EditAttributeDockWidget", "E"))
        self.cboDip.setItemText(1, _translate("EditAttributeDockWidget", "W"))
        self.cboDip.setItemText(2, _translate("EditAttributeDockWidget", "N"))
        self.cboDip.setItemText(3, _translate("EditAttributeDockWidget", "S"))
        self.btnUpdate.setText(_translate("EditAttributeDockWidget", "Update"))
        self.lblDescription.setText(_translate("EditAttributeDockWidget", "Description"))
        self.lblLegend01.setText(_translate("EditAttributeDockWidget", "Legend01"))
        self.lblLegend07.setText(_translate("EditAttributeDockWidget", "Legend07"))
        self.lblLegend06.setText(_translate("EditAttributeDockWidget", "Legend06"))
        self.lblLegend03.setText(_translate("EditAttributeDockWidget", "Legend03"))
        self.lblLegend02.setText(_translate("EditAttributeDockWidget", "Legend02"))
        self.lblLegend04.setText(_translate("EditAttributeDockWidget", "Legend04"))
        self.lblLegend05.setText(_translate("EditAttributeDockWidget", "Legend05"))
        self.lblLayerName.setText(_translate("EditAttributeDockWidget", "Layer Name"))
        self.lblFeature.setText(_translate("EditAttributeDockWidget", "Selected feature ID"))
        self.btnSelectCancel.setText(_translate("EditAttributeDockWidget", "Cancel Select"))

